---
version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: simple
        filename : Thrift.log

loggers:

    qsoWidget:
        level: DEBUG
        handlers: [console]
        propagate: yes

    ContestUi:
        level: ERROR
        handlers: [console]
        propagate: yes

    Contest:
        level: DEBUG
        handlers: [console]
        propagate: yes

    rbn:
        level: ERROR
        handlers: [console]
        propogate: yes

    qtrbn:
        level: DEBUG
        handlers: [console]
        propogate: yes

    dxcc:
        level: ERROR
        handlers: [console]
        propagate: yes

    qtbeacon:
        level: ERROR
        handlers: [console]
        propagate: yes

    __main__:
        level: DEBUG
        handlers: [console]
        propagate: no



